<a href="https://colab.research.google.com/github/ankitmaisuriya/Assignment1/blob/main/numpyexcersie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import numpy as np

a = np.array([1,2,3,4,5])

In [ ]:
b = np.array([1.2,3.4,4.5,5.6,6.7])
c = a + b
c

array([ 2.2,  5.4,  7.5,  9.6, 11.7])

a1=np.array([1,2,3,4,5])
a2=np.array([[1,2,3],[4,5,6]])


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
a4=np.array([1,2,3,4,5],'str')
a4

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [ ]:
a = np.array( [[ 1, 2, 3, 4],[ 5, 6, 7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
print ("Dimensions of a are:", a.ndim)
print ("Shape of a is", a.shape)
print ("Size of a is", a.size)


Dimensions of a are: 2
Shape of a is (3, 4)
Size of a is 12


In [ ]:
a1 = np.empty([3,2],dtype=str)

a2 = np.empty_like(a1)
a2

array([['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

ar = np.zeros([2,2],dtype=int)
ar

In [ ]:
aray1 = np.ones([2,2],dtype=str)
aray1

array([['1', '1'],
       ['1', '1']], dtype='<U1')

In [ ]:
a2 = np.eye(3)
a2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a3 = np.arange(1,10,2,dtype = float)
a3

array([1., 3., 5., 7., 9.])

In [ ]:
a = np.arange(5)
print(a)
a = np.arange(1,10)
print(a)
a = np.arange(1,10,2)
print(a)

[0 1 2 3 4]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [ ]:
a4 = np.linspace(1,10)
a4

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
a5 = np.linspace(0, 1, 5, endpoint= False)
a5

array([0. , 0.2, 0.4, 0.6, 0.8])

In [ ]:
a=np.linspace(1,50,5)
a

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [8]:
import numpy as np
a=np.arange(9)
a
a6 = a.reshape(3,3)
a6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
a = np.array([[12,13],[15,16]])
a
a.T

array([[12, 15],
       [13, 16]])

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a, b))
print(c)

[1 2 3 4 5 6]


In [13]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.concatenate((a,b),axis = 1)
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [16]:
a=np.array([10,20,30,40,50,60])
a
a1=np.split(a,2)
a1

[array([10, 20, 30]), array([40, 50, 60])]

In [20]:
a=np.array([10,20,30,40,50,60])
a
a1=np.split(a,[2,5])
a1

[array([10, 20]), array([30, 40, 50]), array([60])]

In [24]:
a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
a
a1=np.split(a,[2,3],axis=0)
a1

[array([[1, 2],
        [3, 4]]),
 array([[5, 6]]),
 array([[7, 8]])]

In [25]:
a=np.array([1,2,3,4,5])
a
a1=np.insert(a,2,99)
a1

array([ 1,  2, 99,  3,  4,  5])

In [26]:
a=np.array([1,2,3,4,5])
a
a1=np.insert(a,[1,3],[90,80])
a1

array([ 1, 90,  2,  3, 80,  4,  5])

In [28]:
a=np.array([[1,2],[3,4]])
a
a1=np.insert(a,1,[9,9],axis=1)
a1


array([[1, 9, 2],
       [3, 9, 4]])

In [31]:
a = np.array([10, 20, 30, 40, 50])
result = np.delete(a, [2,3])
print(result)

[10 20 50]


In [35]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a1=np.delete(a,1,axis=1)
a1


array([[1, 3],
       [4, 6],
       [7, 9]])

In [36]:
a = np.array([1.7, 2.8, 3.9])
print(a.astype(int))
print(a.astype(str))

[1 2 3]
['1.7' '2.8' '3.9']


In [37]:
a = np.atleast_1d(5)
a
a.shape


(1,)

In [38]:
a = np.atleast_1d([1, 2, 3])
print(a)
print(a.shape)

[1 2 3]
(3,)


In [39]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b.shape)

(2, 3)


In [40]:
a = np.atleast_2d(5)
a
a.shape


(1, 1)

In [41]:
a = np.array([1, 2, 3])
np.atleast_2d(a)


array([[1, 2, 3]])

In [42]:
a = np.atleast_2d([1, 2, 3])
print(a)
print(a.shape)

[[1 2 3]]
(1, 3)


In [43]:
a=np.array([1,2,3])
a
b=np.array([4,5,6])
b
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [46]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a
np.diagonal(a)
np.diagonal(a,offset=1)

array([2, 6])

In [51]:
a=np.arange(16).reshape(4,4)
a
np.trace(a)

np.int64(30)

In [52]:
a=np.array([[1,0,3],[4,5,6]])
a
np.all(a)

np.False_

In [53]:
a=np.array([10,15,20,5])
a
np.where(a>10)

(array([1, 2]),)

In [54]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a ** 2)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]
[1 4 9]


In [61]:
print(np.random.rand(2,3))
print(np.random.randint(1,11,5))
print(np.random.randint(1,10,[2,3]))

[[0.16584767 0.64403001 0.36320691]
 [0.23360871 0.37961658 0.0366119 ]]
[ 7  3  1 10  4]
[[6 3 8]
 [4 2 9]]


In [62]:
a = np.array([10, 20, 30, 40])
a
np.random.choice(a)


np.int64(10)