<a href="https://colab.research.google.com/github/ankitmaisuriya/Assignment1/blob/main/NumpySample/numpyexcersie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import numpy as np

a = np.array([1,2,3,4,5])

In [ ]:
b = np.array([1.2,3.4,4.5,5.6,6.7])
c = a + b
c

array([ 2.2,  5.4,  7.5,  9.6, 11.7])

a1=np.array([1,2,3,4,5])
a2=np.array([[1,2,3],[4,5,6]])


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
a4=np.array([1,2,3,4,5],'str')
a4

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [ ]:
a = np.array( [[ 1, 2, 3, 4],[ 5, 6, 7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
print ("Dimensions of a are:", a.ndim)
print ("Shape of a is", a.shape)
print ("Size of a is", a.size)


Dimensions of a are: 2
Shape of a is (3, 4)
Size of a is 12


In [ ]:
a1 = np.empty([3,2],dtype=str)

a2 = np.empty_like(a1)
a2

array([['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

ar = np.zeros([2,2],dtype=int)
ar

In [ ]:
aray1 = np.ones([2,2],dtype=str)
aray1

array([['1', '1'],
       ['1', '1']], dtype='<U1')

In [ ]:
a2 = np.eye(3)
a2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a3 = np.arange(1,10,2,dtype = float)
a3

array([1., 3., 5., 7., 9.])

In [ ]:
a = np.arange(5)
print(a)
a = np.arange(1,10)
print(a)
a = np.arange(1,10,2)
print(a)

[0 1 2 3 4]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [ ]:
a4 = np.linspace(1,10)
a4

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
a5 = np.linspace(0, 1, 5, endpoint= False)
a5

array([0. , 0.2, 0.4, 0.6, 0.8])

In [ ]:
a=np.linspace(1,50,5)
a

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])